export const listUser = [
  {
    id: 1,
    name: "Supper Admin",
    email: "supperadmin@gmail.com",
    description: "Đéo sợ ai , chỉ sợ mỗi công an !",
    role: 1,
  },
  {
    id: 2,
    name: "To Van Chen",
    email: "tovanchen@gmail.com",
    description: "Đéo sợ ai , chỉ sợ mỗi công an !",
    role: 2,
  },
  {
    id: 3,
    name: "Nguyễn Thị Lệ",
    email: "lenguyen@gmail.com",
    description: "Đéo sợ ai , chỉ sợ mỗi công an !",
    role: 3,
  },
  {
    id: 4,
    name: "Nguyễn Thị Yến",
    email: "yenthi@gmail.com",
    description: "Đéo sợ ai , chỉ sợ mỗi công an !",
    role: 3,
  },
  {
    id: 5,
    name: "Nguyễn Thị Linh",
    email: "linhnguyen@gmail.com",
    description: "Đéo sợ ai , chỉ sợ mỗi công an !",
    role: 3,
  },
  {
    id: 6,
    name: "Nguyễn Thị Dư",
    email: "dunguyen@gmail.com",
    description: "Đéo sợ ai , chỉ sợ mỗi công an !",
    role: 3,
  },
  {
    id: 7,
    name: "Nguyễn Thị Ánh",
    email: "dunguyen@gmail.com",
    description: "Đéo sợ ai , chỉ sợ mỗi công an !",
    role: 3,
  },
  {
    id: 8,
    name: "Nguyễn Thị Sương",
    email: "suongnguyen@gmail.com",
    description: "Đéo sợ ai , chỉ sợ mỗi công an !",
    role: 3,
  },
  {
    id: 9,
    name: "Nguyễn Văn Phong",
    email: "vanphong250895@gmail.com",
    description: "Đéo sợ ai , chỉ sợ mỗi công an !",
    role: 1,
  },
  {
    id: 10,
    name: "Nguyễn Văn Phú",
    email: "phunguyen@gmail.com",
    description: "Đéo sợ ai , chỉ sợ mỗi công an !",
    role: 3,
  }
];
